import React from 'react';
import { CaseStudy, CaseSection, CaseFile, BrandingSettings } from './types';
import { UserIcon, UsersIcon, HeartIcon, SparklesIcon, PuzzlePieceIcon, DocumentTextIcon } from './components/Icons';

export const SECTIONS: CaseSection[] = [
    { id: 'generalInfo', title: 'معلومات عامة', icon: React.createElement(UserIcon) },
    { id: 'familyInfo', title: 'معلومات الأسرة', icon: React.createElement(UsersIcon) },
    { id: 'medicalHistory', title: 'التاريخ الصحي', icon: React.createElement(HeartIcon) },
    { id: 'developmentalHistory', title: 'التاريخ التطوري', icon: React.createElement(SparklesIcon) },
    { id: 'currentPerformance', title: 'مستوى الأداء الحالي', icon: React.createElement(PuzzlePieceIcon) },
    { id: 'finalReport', title: 'التقرير النهائي والتوصيات', icon: React.createElement(DocumentTextIcon) },
];

export const INITIAL_STUDY_DATA: CaseStudy = {
    generalInfo: {
        caseNumber: '',
        childFullName: '',
        gender: '',
        birthDate: '',
        age: '',
        nationality: '',
        birthPlace: '',
        guardianName: '',
        guardianRelation: '',
        contactHome: '',
        contactMobile: '',
        contactWork: '',
        address: '',
        referralSource: '',
        referralDate: '',
        referralReason: '',
    },
    familyInfo: {
        fatherName: '',
        fatherBirthDate: '',
        fatherEducation: '',
        fatherProfession: '',
        motherName: '',
        motherBirthDate: '',
        motherEducation: '',
        motherProfession: '',
        parentsRelationship: '',
        whoChildLivesWith: '',
        familyIncomeSource: [],
        monthlyIncome: '',
        parentsSeparated: false,
        familyPressures: '',
        siblings: [],
        relativesWithConditions: false,
        relativesConditionsDetails: [],
        relativesConditionReport: '',
    },
    medicalHistory: {
        motherAgeAtPregnancy: '',
        pregnancyDuration: '',
        pregnancyType: '',
        pregnancyComplications: '',
        birthType: '',
        birthWeight: '',
        birthLength: '',
        oxygenDeprivation: false,
        apgarScore: '',
        usedBirthTools: false,
        postNatalIssues: '',
        incubator: false,
        incubatorReason: '',
        incubatorDuration: '',
        medications: [],
    },
    developmentalHistory: {
        crawlingAge: '',
        sittingAge: '',
        walkingAge: '',
        firstWordAge: '',
        firstSentenceAge: '',
        teethingAge: '',
        unusualGrowthSymptoms: '',
        languageRegression: '',
        regressionAge: '',
    },
    currentPerformance: {
        selfCareSkills: '',
        socialSkills: '',
        communicationSkills: '',
        academicSkills: '',
        motorSkills: '',
        sensoryProfile: '',
        childInterests: '',
        childDislikes: '',
    },
    finalReport: {
        specialistOpinion: '',
        recommendations: '',
    },
};

export const INITIAL_BRANDING_SETTINGS: BrandingSettings = {
    logo: '',
    organizationName: '',
    address: '',
    contactInfo: '',
};

export const DUMMY_CASE_FILE: CaseFile = {
    id: 'case_dummy_1',
    study: {
        generalInfo: {
            caseNumber: 'C-001',
            childFullName: 'أحمد عبدالله',
            gender: 'ذكر',
            birthDate: '2018-05-15',
            age: '6 سنوات',
            nationality: 'سعودي',
            birthPlace: 'الرياض',
            guardianName: 'عبدالله محمد',
            guardianRelation: 'أب',
            contactHome: '011-1234567',
            contactMobile: '050-1234567',
            contactWork: '011-7654321',
            address: 'حي الياسمين، الرياض، المملكة العربية السعودية',
            referralSource: 'مدرسة الياسمين الابتدائية',
            referralDate: '2024-09-01',
            referralReason: 'صعوبات في النطق والتفاعل الاجتماعي مع أقرانه.',
        },
        familyInfo: {
            fatherName: 'عبدالله محمد',
            fatherBirthDate: '1985-03-20',
            fatherEducation: 'بكالوريوس هندسة',
            fatherProfession: 'مهندس مدني',
            motherName: 'فاطمة علي',
            motherBirthDate: '1988-07-10',
            motherEducation: 'بكالوريوس تربية',
            motherProfession: 'معلمة',
            parentsRelationship: 'جيدة',
            whoChildLivesWith: 'مع كلا الوالدين',
            familyIncomeSource: [],
            monthlyIncome: '25,000 ريال سعودي',
            parentsSeparated: false,
            familyPressures: 'لا توجد ضغوطات كبيرة، ضغط عمل طبيعي.',
            siblings: [
                { id: 'sib_1', name: 'سارة عبدالله', gender: 'أنثى', birthDate: '2015-01-20', age: '9 سنوات', healthStatus: 'سليمة', educationLevel: 'الصف الرابع الابتدائي', profession: 'طالبة' }
            ],
            relativesWithConditions: false,
            relativesConditionsDetails: [],
            relativesConditionReport: '',
        },
        medicalHistory: {
            motherAgeAtPregnancy: '30 سنة',
            pregnancyDuration: '9 أشهر',
            pregnancyType: 'طبيعي',
            pregnancyComplications: 'لا يوجد',
            birthType: 'طبيعية',
            birthWeight: '3.2 كجم',
            birthLength: '50 سم',
            oxygenDeprivation: false,
            apgarScore: '9',
            usedBirthTools: false,
            postNatalIssues: 'يرقان خفيف، تم علاجه بالضوء.',
            incubator: false,
            incubatorReason: '',
            incubatorDuration: '',
            medications: [
                { id: 'med_1', name: 'ريسبردال', dose: '0.5 ملغ مساءً', reason: 'للمساعدة على التركيز وتقليل فرط الحركة', duration: 'مستمر', effects: 'تحسن في التركيز' }
            ],
        },
        developmentalHistory: {
            crawlingAge: '8 أشهر',
            sittingAge: '6 أشهر',
            walkingAge: '13 شهرًا',
            firstWordAge: '15 شهرًا',
            firstSentenceAge: '3 سنوات (تأخر ملحوظ)',
            teethingAge: '7 أشهر',
            unusualGrowthSymptoms: 'لا يوجد',
            languageRegression: 'لا يوجد',
            regressionAge: '',
        },
        currentPerformance: {
            selfCareSkills: 'يعتمد على نفسه في الأكل وارتداء الملابس البسيطة.',
            socialSkills: 'يجد صعوبة في بدء التفاعل مع الأطفال الآخرين، يفضل اللعب بمفرده.',
            communicationSkills: 'يستخدم كلمات مفردة أو جمل قصيرة من كلمتين. يجد صعوبة في التعبير عن احتياجاته ورغباته.',
            academicSkills: 'يعرف بعض الحروف والألوان، لكنه يظهر تشتت انتباه عالي.',
            motorSkills: 'المهارات الحركية الكبرى والدقيقة تبدو طبيعية لعمره.',
            sensoryProfile: 'يظهر حساسية تجاه الأصوات العالية والأماكن المزدحمة.',
            childInterests: 'السيارات، مكعبات البناء، مشاهدة الرسوم المتحركة.',
            childDislikes: 'الأصوات العالية، الأماكن الجديدة، الأطعمة ذات الملمس الغريب.',
        },
        finalReport: {
            specialistOpinion: 'بناءً على البيانات الأولية، يظهر الطفل تأخرًا في النمو اللغوي والاجتماعي. قد تكون هناك مؤشرات لاضطراب طيف التوحد أو اضطراب في التواصل الاجتماعي. يحتاج إلى تقييم شامل.',
            recommendations: '- تقييم نطق ولغة.\n- تقييم سلوكي ونفسي شامل.\n- جلسات تخاطب فردية.\n- برنامج تدخل مبكر لتنمية المهارات الاجتماعية.',
        },
    }
};